name: Fetch EFT Version

on:
  push:
    branches:
      - main

jobs:
  fetch-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.15.0

      - name: Install dependencies
        run: npm install site-utils

      - name: Fetch game version
        run: |
          const { Site } = require('site-utils');

          async function fetchGameVersion() {
              let currentVersion = '';
              const url = 'https://escapefromtarkov.fandom.com/wiki/Changelog';

              try {
                  const document = await Site.getDocument(url);
                  const getCurrentGameVersion = document.querySelector('strong.mw-selflink.selflink')?.textContent;

                  if (getCurrentGameVersion) {
                      const parsedVersion = getCurrentGameVersion.match(/\d\.*.*/g)?.[0];
                      if (parsedVersion) {
                          currentVersion = parsedVersion;
                      }
                  }
              } catch (error) {
                  console.error('Error fetching game version:', error.message);
                  return; // Exit the workflow if there's an error
              }

              console.log('Current game version:', currentVersion);

              // Write to eft_version.json
              const fs = require('fs');
              fs.writeFileSync('eft_version.json', JSON.stringify({ version: currentVersion }, null, 2));
          }

          fetchGameVersion();

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add eft_version.json
          git commit -m "Update EFT version"
          git push
